<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/11/06 02:28:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=webdevel',
  'username' => 'webdevel',
  'password' => 'webdevel',
  'name' => 'doctrine',
)),);
