<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/02 15:32:50

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=webdevel',
  'username' => 'webdevel',
  'password' => 'webdevel',
  'name' => 'doctrine',
)),);
