<?php
// auto-generated by sfViewConfigHandler
// date: 2012/04/02 15:32:50
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'WebDevel.cl', false, false);
  $response->addMeta('description', 'Diseño &amp; Desarrollo Web', false, false);
  $response->addMeta('keywords', 'diseño web, desarrollo, php, symfony', false, false);
  $response->addMeta('language', 'es', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('style.css', '', array ());
  $response->addStylesheet('skins/dark.css', '', array ());
  $response->addStylesheet('custom.css', '', array ());
  $response->addStylesheet('schemes/orange.css', '', array ());
  $response->addStylesheet('scripts/nivo-slider.css', '', array ());
  $response->addStylesheet('scripts/prettyPhoto.css', '', array ());
  $response->addStylesheet('ie7.css', '', array (  'condition' => 'IE 7',));
  $response->addJavascript('jquery-1.6.2.min.js', '', array ());
  $response->addJavascript('contact-form.js', '', array ());
  $response->addJavascript('custom.js', '', array ());
  $response->addJavascript('jquery.nivo.slider.pack.js', '', array ());
  $response->addJavascript('jquery.prettyPhoto.js', '', array ());
  $response->addJavascript('jquery-ui-personalized-1.5.2.packed.js', '', array ());
  $response->addJavascript('styleswitcher.js', '', array ());
  $response->addJavascript('jquery.quicksand.min.js', '', array ());
  $response->addJavascript('jquery.easing.js', '', array ());


